### ISSUE TITLE
Question about .Page.Params.redirect_url

### ISSUE THREAD

**Issue by mandaris** [chrishannah/Pure#8]
I'm working on the transition to Hugo .91 and I'm seeing an issue with line 4 of navigation.html.

`{{ if .Page.Params.redirect_url }}`

What is this line supposed to be doing?

**Comment by chrishannah** [comment]
That's a very good question. I'm pretty sure I knew what it was when I first wrote the theme, but it appears as if it's not needed, so I've removed it.

**Comment by mandaris** [comment]
Found this on the release notes page.
https://github.com/gohugoio/hugo/releases/tag/v0.92.0

> The .Page methods marked as deprecated in Hugo 0.55 are now removed. They have been logged as an ERROR for a long time now and you will still get a clear error if you use them.
